### PR TITLE
Use value_and_pullback_function as a primitive

### LINKED ISSUE #34: Make value_and_pullback_function a primitive instead of pullback_function
Currently the internals use closures to avoid computing the primal more than once, but it would be easier to read, simpler, and more consistent with ChainRules, Zygote, Diffractor, etc to instead make `value_and_pullback_function` the primitive. Should come after #4.

Not certain if the same should be done for `pushforward_function`.

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #34. Breaking change marked with `-DEV` version number in case it is merged before #35.

### CODE REVIEW

**Comment by mohamed82008** [comment]
This PR needs more thinking. I think when using the Jacobian as a primitive, deriving the `value_and_pullback function` won't be possible. Only the `value and pullback_function` is. So it might make sense to define the `value_and_pullback_function/value_and_pushforward_function` to throw when the Jacobian is used as a primitive. That is users shouldn't expect to use these 2 functions for such a backend or at least the methods won't be define automatically.

**Comment by mohamed82008** [comment]
Ah sorry I meant to comment on the other PR. Anyways, I suggest merging this PR and #34.

**Comment by sethaxen** [comment]
> Ah sorry I meant to comment on the other PR. Anyways, I suggest merging this PR and #34 and updating the README once.

I assume you mean #35? That PR already updates the ReadMe for the redefinition of `value_and_pullback_function`. Currently definition of a primitive is not documented, so we need no updates in this PR.

**Comment by mohamed82008** [comment]
I want to take a stab at this myself if you don't mind. I will open another PR.

**Comment by gdalle** [comment]
@devmotion should we close this one?

**Comment by devmotion** [comment]
Probably. We can always re-open if it is preferred over https://github.com/JuliaDiff/AbstractDifferentiation.jl/pull/93.

**Pull request closed without merging**
